name: Combined Web & API Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome (for UI tests)
        uses: browser-actions/setup-chrome@v1

      - name: Grant permission to execute Gradle
        run: chmod +x ./gradlew

      # Run Web UI tests
      - name: Run Web UI Tests
        run: ./gradlew test --tests "web."

      # Run API tests
      - name: Run API Tests
        run: ./gradlew test --tests "api."

      # Debug: list report files
      - name: List Report Files (Debug)
        run: |
          echo ":: Web Reports"
          ls -R target/web || echo "No web report files found"
          echo ":: API Reports"
          ls -R reports || echo "No API report files found"

      # Upload Web UI reports
      - name: Upload Web UI Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-ui-report
          path: |
            target/web/cucumber-html-report.html
            target/web/cucumber-report.json

      # Upload API reports
      - name: Upload API Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: |
            reports/html/api-report.html
            reports/json/api-report.json